### ISSUE TITLE
menuconfig does not work

### ISSUE THREAD

**Issue by bradprob** [szermatt/mistty#10]
Hi,
mistty does not show menuconfig correctly. The following warning is shown:

**WARNING: Menuconfig may fail because of the TERM environment variable is set to "xterm". Please consult the documentation of your terminal to set it up. Some good, proved to been working setups include xterm-256color, screen-256color, rxvt-unicode-256color, alacritty.**

**Comment by szermatt** [comment]
The correct value of `TERM` for mistty is `eterm-color`. This is set by default, but apparently something sets it to `xterm` on your system. 

Please retry with TERM set to eterm-color.

To be sure, you are talking about the tool that's in the linux kernel source, launched by 'make menuconfig' ? It worked for me with TERM set to eterm-color, at least for linux-6.5.7.

**Comment by szermatt** [comment]
If `TERM` is overridden, it's likely that `TERMCAP` and `TERMINFO` are overridden as well. In such a situation, just setting `TERM` back to `eterm-color` might not be enough. 

You might also want to check that the Emacs installation has added `/etc/terminfo/e/eterm-color` to your system. If not, you can find that file in the Emacs source repository or package under `etc/e/eterm-color`.
