### ISSUE TITLE
Control characters visible in prompt

### ISSUE THREAD

**Issue by candera** [szermatt/mistty#11]
My command prompt generation is somewhat involved (see [here](https://github.com/candera/scripts/blob/197ffe270f1ea62eec7abdb78d686b520bc9cdc2/.bashrc#L374)), but the problematic part appears to be my use of [gitstatus](https://github.com/romkatv/gitstatus). Under mistty, I see some control characters in my prompt: 

![Untitled](https://github.com/szermatt/mistty/assets/28521/b81100ff-952d-476d-91cf-57d00bf08e88)

**Comment by szermatt** [comment]
It looks like gitstatus surrounds color changes with `\001` and `\002`. That makes no sense. It's definitely not a nonstandard terminal sequence. gistatus is probably hoping that the terminal will just ignore these, which is usually the case, but nothing guarantees it. 

In Emacs, control characters are normally displayed, which is a nice thing to have even in the terminal.

I'd suggest just sanitizing the output of gitstatus with:

```
echo -e ${GITSTATUS_PROMPT} | tr -d '\001\002'
```

You won't lose anything by always doing that, but you can, if you prefer, do that only on Emacs terminal if you make this conditional on `TERM` being `eterm-color`.

**Comment by candera** [comment]
Cool, I will try that. Thanks for troubleshooting this, especially since it's not your problem! :)

**Comment by candera** [comment]
Yep, that works, in and outside of emacs.

**Comment by candera** [comment]
Closing - not an issue with mintty.
