### ISSUE TITLE
Unhide cursor by killing cursor-type local variable, not resetting it locally to t

### ISSUE THREAD

**Issue by dcolascione** [szermatt/mistty#25]
`cursor-type` becomes automatically buffer-local when set. `mistty` sets `cursor-type` to `nil` to implement cursor hiding and undoes the cursor hiding by setting it to `t`. But this latter assignment is wrong in the case that the user has globally customized the cursor type. Instead of setting `cursor-type` to `t` in `mistty-term.el`, we should use `kill-local-variable` to restore `cursor-type` to the value it'd otherwise have had.

**Comment by szermatt** [comment]
Yes, good point. I'll do that. Thanks!

**Comment by dcolascione** [comment]
Make sure to grab both places `cursor-type` is set. You could also remember whether the user set cursor-type in the mode hook and, if so, reset the cursor-type to that value instead of killing the local variable entirely (in case somebody wants to customize the cursor type for just the mistty buffer)
