### ISSUE TITLE
Investigate issues with corfu

### ISSUE THREAD

**Issue by szermatt** [szermatt/mistty#5]
The goal of this bug is to figure out what can be done, if anything, to make corfu work on MistTTY buffers. 

EDIT: When this issue was first written, it looked like corfu was confused by the fact that beginning-of-line doesn't stop before the prompt, but it doesn't seem to be that, so the issue description was updated.

**Comment by AkibAzmain** [comment]
What makes you think Corfu needs to know the exact position?  Anyway, I tried to investigate why Corfu is not working, and only of the reasons is that the value of `(corfu--auto-tick)` changes between the post-command-hook and the idle timer, i.e. the buffer gets modified between this time.

**Comment by szermatt** [comment]
> What makes you think Corfu needs to know the exact position? 

When I tried it, it complained about not understanding my prompt. I looked into the code and saw that it relied on `(line-beginning-position)` not going past the prompt when analyzing the current line. I assumed that was the problem you were having. 

What does the problem you're having look like?

**Comment by szermatt** [comment]
> the value of (corfu--auto-tick) changes between the post-command-hook 
> and the idle timer, 

It looks like corfu is too clever for its own good. It refuses to be fooled. There will indeed be changes happening in the background as text added by Emacs command gets sent to the shell and then sent back to be displayed on the terminal.

**Comment by AkibAzmain** [comment]
> I looked into the code and saw that it relied on (line-beginning-position) not going past the prompt when analyzing the current line.

No, I can't find anything such in corfu.el, maybe the CAPF is calling that?  bash-completion needs to know the beginning of line.

> What does the problem you're having look like?

Corfu auto-completion doesn't initiate at all, and if i manually initiate with `M-x completion-at-point`, the popup appears but it doesn't respond and the popup doesn't go away until I go to some other buffer and invoke Corfu there.

**Comment by szermatt** [comment]
As mentioned in the comments, corfu-auto can be made to work as explained on https://mistty.readthedocs.io/en/latest/usage.html#emacs-autocomplete
