### ISSUE TITLE
Behaviour of recenter-top-bottom

### ISSUE THREAD

**Issue by ashlineldridge** [szermatt/mistty#6]
Thanks for this cool package.

What is the intended behaviour of the `C-l` / `recenter-top-bottom` command in mistty? Personally, I'd love it if `recenter-top-bottom` behaved the same way as in eshell which allows you to recenter the prompt line and then begin typing. However, in mistty once you begin typing the prompt moves back to the original position close to the bottom of the window. Is there anything that would prevent mistty from adopting the typical behaviour of `C-l`?

**Comment by szermatt** [comment]
The jumping behavior is a ugly hack to avoid ever getting into situations where the prompt isn't visible, inspired from comint. I don't like it either and I'd like to change it. 

I'll have a look at how eshell behaves and see whether I can do the same thing. Thank you for the pointer!

**Comment by szermatt** [comment]
With the latest change, scrolling should behave normally. It looks good to me, but I think this will require more time and testing. 
Does it behave as you would expect?
