### ISSUE TITLE
misty.el: typo in mistty defun prevents creation in other window

### ISSUE THREAD

**Issue by jcbagneris** [szermatt/mistty#8]
Hello there,

Thanks for misTTY!

I guess there is a small typo on line 825 in `mistty.el`, in the defun of `mistty`, to create a missty in an other window, the call should be (note the dash)
```
(mistty-create-other-window)
```
instead of
```
(mistty-create other-window)
```
as, as far as I can see,  `mistty-create` takes 2 optional parameters, `command` and `other-window`.

Thank you!

**Comment by szermatt** [comment]
Oh! That's a silly bug. Thank you for reporting it!
